### ISSUE TITLE
example for fastest config

### ISSUE THREAD

**Issue by yannick** [libmir/asdf#103]
@9il  could you edit the readme so there is a copy paste dub config for the fastest possible config
(use ldc + all optimizations) ? 
or add an extra example project/benchmark and link that in the readme section.

i just read through the readme and its not 100% clear on how to archieve this.

>Instead of using -mcpu=native, you may specify additional instruction set for a target with -mattr. For example, -mattr=+sse4.2.

this leaves it completely open what the fastest config is. 

alternatively the https://github.com/libmir/asdf#asdf-example-incomplete example could be edited to contain a shebang inline dub config so it can be copy pasted to run

**Comment by 9il** [comment]
#106
