### ISSUE TITLE
Request on asserts 

### ISSUE THREAD

**Issue by Laeeth** [libmir/asdf#132]
Hi Ilya

We are going to be using asdf for market data retrieval across the firm.  Legacy format is json. 

Would it be possible to have a dub build configuration that changes the implementation of assert to call enforce instead?  Json may not be well formed and its a bad user experience if the program crashes.

**Comment by 9il** [comment]
Hi Laeeth

ASDF definitely should never assert for a wrong input, instead, an exception should be thrown. I thought I replaced all user-level asserts in ASDF parsing, but another one has been found and replaced with `AsdfException` in `v0.5.2`. Also, I have replaced an assert in `AsdfNode`, not sure if this part of asdf was ever used outside of Tamdia, but now we don't have user-level asserts (if I didn't miss something). All remaining asserts should either be thrown in CTFE or they check internal asdf logical issues and shouldn't be thrown in application code.
