### ISSUE TITLE
Cannot serialize objects in const member functions

### ISSUE THREAD

**Issue by yshui** [libmir/asdf#134]
```d
struct A {
    string str;
}
struct B {
    A a;
    string serialize() const {
        return asdf.serializeToJson(a);
    }
}
```

`B.serialize` serializes `A` to an empty object, because the test `isReadableAndWritable!(a, "str")` fails.

**Comment by 9il** [comment]
Looks like you have used an older version of ASDF or older compiler.
The unittest pass the CI https://travis-ci.org/libmir/asdf/builds/624698254
