### ISSUE TITLE
Would you add asdf to langeuage benchmark :)

### ISSUE THREAD

**Issue by zoujiaqing** [libmir/asdf#2]
https://github.com/kostya/benchmarks/tree/master/json

**Comment by 9il** [comment]
currently working on mir-ion - asdf successor. I will add them both when ready. Thanks)

**Comment by zoujiaqing** [comment]
look forward to!

**Comment by 9il** [comment]
Added both Asdf and Ion, https://github.com/kostya/benchmarks/pull/330
Also waiting for https://github.com/kostya/benchmarks/pull/335 be merged to make the benchmark more fair. 

The Ion advantage is that it can build a DOM, its DOM is Amazon's Ion with symbol tables, so it us 5-10 times smaller than other libraries with DOM.  In addition, Ion can read from directly from files (implemented) or from streams (on request) without allocating memory for the whole input.
