### ISSUE TITLE
asdf has compatible JSONValue?

### ISSUE THREAD

**Issue by zoujiaqing** [libmir/asdf#3]
```CPP
#include "simdjson.h"

int main(void) {
  simdjson::dom::parser parser;
  simdjson::dom::element tweets = parser.load("twitter.json");
  std::cout << tweets["search_metadata"]["count"] << " results." << std::endl;
}
```

So asdf code:
```D
tweets["search_metadata", "count"];
```

JSONValue code:
```D
tweets["search_metadata"]["count"].get!uint;
```

**Comment by 9il** [comment]
Could you please clarify what means compatible?

**Comment by 9il** [comment]
ASDF doesn't use Phobos JSONValue.

**Comment by zoujiaqing** [comment]
I meanns use more common ways of using..

**Comment by 9il** [comment]
Like this one?
```d
import std.conv: to;
auto integer = tweets["search_metadata", "count"].to!int;
```

**Comment by zoujiaqing** [comment]
Like this one:
```D
tweets["search_metadata"]["count"];
```

**Comment by 9il** [comment]
Maybe [`Asdf`](http://asdf.libmir.org/asdf_asdf.html#.Asdf) type is what you are looking for.

**Comment by 9il** [comment]
If you are asking about if Asdf is compatible with JSONValue. No, it isn't.

**Comment by 9il** [comment]
Asdf can now be de/serialized to/from `mir.algebraic` types.

https://forum.dlang.org/thread/itdobhbjiynjtijschoe@forum.dlang.org
