### ISSUE TITLE
0.5 => 0.6 is a breaking change, can you add to doc & some explanation?

### ISSUE THREAD

**Issue by mw66** [libmir/asdf#6]
Hi,

Just noted the change from 0.5.x serializedXxx => 0.6.x serdeXxx, e.g.

@serializedAs => @serdeProxy

What's the reason for this kind of change? IMO, serialized is much readable English than serde.

I googled a bit, and only find: https://github.com/serde-rs/serde

But I suppose this code base is a clean D implementation, and has nothing to do with that Rust package.

So why? If it's really needed, can you also add to the doc, e.g. also the release tag for the explanation.

Thanks.

**Comment by mw66** [comment]
Oh, it's not breaking change, but deprecation change:

https://github.com/libmir/asdf/blob/master/source/asdf/serialization.d#L2762

but I still don't understand the "serde" part.

**Comment by 9il** [comment]
SERializing and DEserializing, like Rust's lib
